### ISSUE TITLE
Bug: page 23 section 12.5 (​pop​ ​my-list​) returns 1, NOT (2 3 4)

### ISSUE THREAD

**Issue by muyinliu** [ashok-khanna/lisp-notes#2]
At page 23 section 12.5, `(pop my-list)` returns `1`, NOT `(2 3 4)`(thought `my-list` become `(2 3 4)` after `pop`

And other notes:

- variable `my-list​` should be renamed to `*my-list​*` as it's defined as a global variable with `defparameter`
- should point out that `push` and `pop` would change variable `my-list`

Thanks for sharing.

**Comment by ashok-khanna** [comment]
Dear muyinliu,

Many thanks for your note. 

Yes indeed, (pop my-list) returns one, the (2 3 4) in the comment referred to the next line. I think the  last sentence notes that they are destructive operations that change the list. I have added in the word "original" to make this even more clear. I have also made it more explicit on the return values of the functions themselves -- thank you for the suggestion.

Below is the revised extract.

Finally, I debated with myself just now on whether to `*my-list*`. Issue is I would have to do it everywhere to be consistent and that would create too much syntactical overhead for the beginner (what does * * refer to they will ask, until they get comfortable with the terminology). I have the same issue in that I do not follow correct indenting rules all the time, because I want to fit everything nicely into the pages and sometimes need to condense things. At the start of the guide, it is noted that defparameter should be named as `*name*`, and I will debate with myself whether to 'handhold' the readers more on the fact I don't follow this guide throughout the text + not following indenting rule, purely for teaching / cosmetic purposes. For now, I have tried to minimise handholding but I will let you know if my views change. I need to think carefully, I think it is a valid point you make.

```
We can use lists as pushdown stacks. The macro PUSH can be used to push an element to the front of the list, while the macro POP can remove and return the first element of the list. Both are destructive operations as they directly change the **original** lists in question. For example:

(defparameter my-list '(2 3 4))

(push 1 my-list)		; Returns (1 2 3 4)	
My-list				; Returns (1 2 3 4)

(pop my-list)			; Returns 1, the car of the list
my-list				; Returns (2 3 4)
```

**Comment by ashok-khanna** [comment]
Dear muyinliu,

Hope you are well. Please let me know if you have any further comments, or otherwise I will close this issue in 48 hours (no need to respond - just checking out of courtesy, but I'm happy with the resolution of the query and also thank you for your feedback).
